=encoding utf-8

=head1 NAME

autocomplete-ALL-the-things - an urxvt plugin allowing user to easily complete words

=head1 INSTALLATION

Copy the F<autocomplete-ALL-the-things> file to the urxvt perl-lib directory (default: F<~/.urxvt/ext/>).

Add the following lines to your F<~/.Xresources> (or F<~/.Xdefaults>):

  URxvt.perl-ext-common: ...,autocomplete-ALL-the-things
  URxvt.keysym.M-slash:  perl:aAtt:complete

=head1 DESCRIPTION

Completes the currently typed word using the other words visible in the urxvt window.

For example the terminal looks like this:

  foo bar baz
  >> _

I type 'f':

  foo bar baz
  >> f_

Now I can use autocomplete-ALL-the-things to expand the 'f' to 'foo'.

  foo bar baz
  >> foo_

If I had typed 'b', it would be expanded to 'baz' and not 'bar' as the rightmost match is used.

It was strongly inspired by I<dabbrev> feature in GNU Emacs and later by
L<skeleton-complete|https://github.com/baohaojun/skeleton-complete> by Bao
Haojun.

For more advanced usage, see readme for I<skeleton-complete>.

To undo the completion, just press the defined key a second time.

=head1 USAGE

Just press the defined key (in the example above: Alt-slash) to complete the word at point.

=head1 ACKNOWLEDGMENTS

Thanks to Bao Haojun for the great idea of L<skeleton-complete|https://github.com/baohaojun/skeleton-complete>.

=head1 COPYRIGHT

Copyright (C) 2012-2013  Wojciech Siewierski

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
